# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(max_length=200)),
                ('erstellt_von', models.CharField(max_length=200)),
                ('inhalt', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Anfragen',
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=3)),
                ('ort', models.CharField(max_length=300)),
                ('zeit', models.CharField(max_length=300)),
                ('kapazitaet', models.IntegerField(default=0)),
                ('sonstiges', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('nationalitaet', models.CharField(blank=True, max_length=200)),
                ('muttersprache', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=3)),
                ('status', models.IntegerField(choices=[(1, 'Warteliste'), (2, 'Bearbeitung'), (3, 'Schueler')], default=2)),
                ('zeiten', models.IntegerField(choices=[(1, 'Vormittags'), (2, 'Nachmittags'), (3, 'Abends'), (4, 'Unbekannt'), (5, 'Egal')], default=4)),
                ('sonstiges', models.TextField(blank=True, max_length=500)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('wait_date', models.DateTimeField(blank=True, null=True)),
                ('kurse', models.ManyToManyField(blank=True, to='courses.Kurs')),
            ],
            options={
                'verbose_name_plural': 'Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('levels', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(default='test@test.com', max_length=200)),
                ('addresse', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=200)),
                ('sonstiges', models.TextField(blank=True, max_length=500)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('kurse', models.ManyToManyField(blank=True, to='courses.Kurs')),
            ],
            options={
                'verbose_name_plural': 'Trainer',
            },
        ),
        migrations.AddField(
            model_name='kurs',
            name='teilnehmers',
            field=models.ManyToManyField(blank=True, to='courses.Teilnehmer'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='courses.Trainer'),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='teilnehmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Teilnehmer'),
        ),
    ]
